// Built-in catalog of common exercises, grouped by category. Used to power the
// type-ahead suggestions in the workout editor. Custom names are still allowed —
// these are only suggestions.
export const EXERCISE_LIBRARY = {
  Chest: [
    'Push-ups',
    'Incline Push-ups',
    'Diamond Push-ups',
    'Wide Push-ups',
    'Bench Press',
    'Incline Bench Press',
    'Dumbbell Press',
    'Chest Fly',
    'Cable Crossover',
    'Dips',
  ],
  Back: [
    'Pull-ups',
    'Chin-ups',
    'Inverted Rows',
    'Bent-over Row',
    'Dumbbell Row',
    'Lat Pulldown',
    'Seated Cable Row',
    'Deadlift',
    'Superman',
    'Face Pull',
  ],
  Shoulders: [
    'Overhead Press',
    'Arnold Press',
    'Lateral Raise',
    'Front Raise',
    'Rear Delt Fly',
    'Pike Push-ups',
    'Shrugs',
    'Upright Row',
  ],
  Arms: [
    'Bicep Curl',
    'Hammer Curl',
    'Concentration Curl',
    'Tricep Extension',
    'Tricep Dips',
    'Skull Crushers',
    'Close-grip Push-ups',
    'Chin-ups',
  ],
  Legs: [
    'Squats',
    'Goblet Squat',
    'Front Squat',
    'Lunges',
    'Reverse Lunges',
    'Walking Lunges',
    'Bulgarian Split Squat',
    'Step-ups',
    'Romanian Deadlift',
    'Leg Press',
    'Leg Curl',
    'Leg Extension',
    'Calf Raises',
    'Glute Bridge',
    'Hip Thrust',
    'Wall Sit',
  ],
  Core: [
    'Plank',
    'Side Plank',
    'Crunches',
    'Bicycle Crunches',
    'Sit-ups',
    'Leg Raises',
    'Russian Twists',
    'Mountain Climbers',
    'Flutter Kicks',
    'Dead Bug',
    'Hollow Hold',
    'V-ups',
    'Hanging Knee Raises',
    'Ab Wheel Rollout',
  ],
  Cardio: [
    'Burpees',
    'Jumping Jacks',
    'High Knees',
    'Butt Kicks',
    'Jump Rope',
    'Sprints',
    'Box Jumps',
    'Jump Squats',
    'Skaters',
    'Tuck Jumps',
    'Bear Crawl',
    'Battle Ropes',
    'Rowing',
    'Cycling',
    'Running',
  ],
  'Full Body': [
    'Thrusters',
    'Clean and Press',
    'Kettlebell Swing',
    'Turkish Get-up',
    'Man Makers',
    'Devil Press',
    'Wall Balls',
    'Sled Push',
  ],
  Stretching: [
    'Hamstring Stretch',
    'Quad Stretch',
    'Hip Flexor Stretch',
    'Child’s Pose',
    'Cat-Cow',
    'Downward Dog',
    'Cobra Stretch',
    'Shoulder Stretch',
  ],
}

// Flat, de-duplicated list of all exercise names for the <datalist>.
export const EXERCISE_NAMES = [
  ...new Set(Object.values(EXERCISE_LIBRARY).flat()),
].sort((a, b) => a.localeCompare(b))
